'use client';
import { useTranslation } from 'react-i18next';
import type { DocumentFormData } from '../../types';

function makeComplaintText(fields: DocumentFormData, title: string, law: string): string {
  return `${title.toUpperCase()}

TO,
${fields.respondentName || 'The Appropriate Authority'}
${fields.respondentAddress || ''}

SUBJECT: Complaint / Grievance Application

Respected Sir/Madam,

I, ${fields.name || '[Your Name]'}, residing at ${fields.address || '[Your Address]'}, hereby lodge this formal complaint.

Date of Incident: ${fields.incidentDate || '[Date]'}

Description of Grievance:
${fields.description || '[Describe the issue in detail]'}

${fields.amount ? 'Amount Involved: Rs. ' + fields.amount : ''}

I request your urgent intervention and appropriate action under ${law}.

I have attached all relevant documentation in support of this complaint. I request resolution within 30 days as per applicable law.

Yours sincerely,

____________________
${fields.name || '[Signature]'}
${fields.address || ''}
Phone: ${fields.phone || ''}
Date: ${fields.date || new Date().toLocaleDateString('en-IN')}

---
This document was generated by NyayaSaathi (nyayasaathi.in).
DISCLAIMER: This is a template. Review before submission. Not legal advice.
`;
}

function makeRTIText(fields: DocumentFormData): string {
  return `RTI APPLICATION UNDER RIGHT TO INFORMATION ACT, 2005

TO,
The Public Information Officer
${fields.authority || '[Public Authority / Department Name]'}

SUBJECT: Application under Section 6(1) of the Right to Information Act, 2005

Respected Public Information Officer,

I, ${fields.name || '[Your Name]'}, a citizen of India, residing at ${fields.address || '[Your Address]'}, wish to obtain the following information under the Right to Information Act, 2005:

INFORMATION REQUESTED:
${fields.infoRequested || '[Please specify the information you are requesting]'}

I am enclosing the prescribed application fee of Rs. 10/- via [Postal Order / IPO / Online Transfer].

Kindly provide the above information within 30 days as mandated by Section 7(1) of the RTI Act, 2005.

Yours faithfully,

____________________
${fields.name || '[Your Name]'}
${fields.address || '[Your Address]'}
Phone: ${fields.phone || ''}
Date: ${fields.date || new Date().toLocaleDateString('en-IN')}

---
This document was generated by NyayaSaathi (nyayasaathi.in).
DISCLAIMER: This is a template. Review before submission. Not legal advice.
`;
}

function makeConsumerText(fields: DocumentFormData): string {
  return `CONSUMER COMPLAINT
Under Consumer Protection Act, 2019

TO,
The District Consumer Disputes Redressal Commission
${fields.respondentAddress || '[District Name]'}

SUBJECT: Complaint under Section 35 of the Consumer Protection Act, 2019

Respected Members of the Commission,

I, ${fields.name || '[Your Name]'}, residing at ${fields.address || '[Your Address]'}, am filing this complaint against:

OPPOSITE PARTY:
${fields.respondentName || '[Company/Seller Name]'}
${fields.respondentAddress || '[Company Address]'}

1. DETAILS OF TRANSACTION:
Date of Purchase/Service: ${fields.incidentDate || '[Date]'}
Amount Paid: ${fields.amount ? 'Rs. ' + fields.amount : '[Amount]'}

2. GRIEVANCE / DEFICIENCY:
${fields.description || '[Describe the product defect or service deficiency in detail]'}

3. PRAYER / RELIEF SOUGHT:
I request the Commission to direct the Opposite Party to:
a) Refund the amount of ${fields.amount ? 'Rs. ' + fields.amount : '[Amount]'} with interest.
b) Pay compensation for mental agony and litigation costs.
c) Any other relief the Commission deems fit.

Yours faithfully,

____________________
${fields.name || '[Your Name]'}
Phone: ${fields.phone || ''}
Date: ${fields.date || new Date().toLocaleDateString('en-IN')}

---
This document was generated by NyayaSaathi (nyayasaathi.in).
DISCLAIMER: This is a template. Review before submission. Not legal advice.
`;
}

function makeFIRText(fields: DocumentFormData): string {
  return `FIR DRAFT / POLICE COMPLAINT
Under Section 154 CrPC, 1973

TO,
The Station House Officer (SHO)
${fields.respondentName || '[Police Station Name]'}
${fields.respondentAddress || '[Police Station Address]'}

SUBJECT: Request for FIR registration under Section 154 CrPC

Respected Sir/Ma'am,

I, ${fields.name || '[Your Name]'}, residing at ${fields.address || '[Your Address]'},
Phone: ${fields.phone || ''}, hereby submit this written complaint and request you
to register an FIR immediately.

DATE OF INCIDENT: ${fields.incidentDate || '[Date]'}
TIME OF INCIDENT: ${fields.incidentTime || '[Time]'}
LOCATION OF INCIDENT: ${fields.incidentLocation || '[Location]'}

DESCRIPTION OF INCIDENT:
${fields.description || '[Describe what happened in detail]'}

ACCUSED (Known / Suspected):
${fields.accusedNames || '[Names of accused persons]'}

WITNESSES:
${fields.witnessNames || '[Names of witnesses]'}

EVIDENCE / DOCUMENTS:
${fields.evidenceList || '[List of evidence attached]'}

I request you to:
1. Register an FIR against the accused under appropriate sections of law.
2. Take immediate legal action and investigate the matter.
3. Provide me a free copy of the FIR after registration (Section 154(2) CrPC).

NOTE: If you refuse to register the FIR, I reserve the right to approach the
Superintendent of Police or Magistrate under Section 156(3) CrPC.

Yours sincerely,

____________________
${fields.name || '[Your Name]'}
${fields.address || '[Your Address]'}
Phone: ${fields.phone || ''}
Date: ${fields.date || new Date().toLocaleDateString('en-IN')}

---
This document was generated by NyayaSaathi (nyayasaathi.in).
DISCLAIMER: This is a template. Review before submission. Not legal advice.
`;
}

interface Props {
  fields: DocumentFormData;
  templateType: string;
  situationTitle: string;
  lawCitation: string;
}

export default function DocumentPreview({ fields, templateType, situationTitle, lawCitation }: Props) {
  const { t } = useTranslation();
  const text = templateType === 'rti'
    ? makeRTIText(fields)
    : templateType === 'fir'
    ? makeFIRText(fields)
    : templateType === 'consumer'
    ? makeConsumerText(fields)
    : makeComplaintText(fields, situationTitle, lawCitation);

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <h3 style={{ fontSize: 14, fontWeight: 700, color: '#1A1A1A', marginBottom: 12, display: 'flex', alignItems: 'center', gap: 8 }}>
        <span style={{ width: 8, height: 8, borderRadius: '50%', background: '#923c22', display: 'inline-block' }} />
        {t('generate.preview_title')}
      </h3>
      <div style={{
        flex: 1, background: '#FDFAF7', border: '1px solid #EAE1DA', borderRadius: 10,
        padding: '20px 24px', fontFamily: 'Courier New, monospace', fontSize: 12,
        lineHeight: 1.8, color: '#1e293b', overflowY: 'auto', whiteSpace: 'pre-wrap',
        minHeight: 400, position: 'relative',
      }}>
        <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', opacity: 0.04, fontSize: 48, fontWeight: 900, color: '#923c22', pointerEvents: 'none', userSelect: 'none', transform: 'rotate(-35deg)' }}>
          NyayaMitra
        </div>
        {text}
      </div>
    </div>
  );
}

export { makeComplaintText, makeRTIText, makeFIRText, makeConsumerText };
