-- =============================================================================
-- V1__create_schema.sql
-- NyayaMitra — Initial PostgreSQL Schema
--
-- Managed by Flyway. DO NOT edit this file after deployment.
-- For schema changes, create V2__*.sql, V3__*.sql etc.
--
-- Tables correspond 1-to-1 with @Entity classes in com.nyayamitra.entity.
-- Run order follows FK dependency: parent tables before child tables.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. USERS & AUTH
-- Entity: AppUser (@Table name = "app_users")
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS app_users (
    id          BIGSERIAL       PRIMARY KEY,
    username    VARCHAR(255)    NOT NULL UNIQUE,
    email       VARCHAR(255)    NOT NULL UNIQUE,
    password    VARCHAR(255)    NOT NULL,
    enabled     BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- @ElementCollection for Set<String> roles
-- @CollectionTable(name = "user_roles")
CREATE TABLE IF NOT EXISTS user_roles (
    user_id     BIGINT          NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    role        VARCHAR(100)    NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. SITUATIONS (parent)
-- Entity: Situation (@Table name = "situations")
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS situations (
    db_id           BIGSERIAL       PRIMARY KEY,
    -- Business-key slug from original MongoDB "id" field (e.g. "landlord-dispute")
    situation_id    VARCHAR(255)    NOT NULL UNIQUE,
    category        VARCHAR(255)    NOT NULL,
    icon            TEXT,
    title_en        TEXT            NOT NULL,
    title_hi        TEXT            NOT NULL,
    description_en  TEXT,
    description_hi  TEXT,
    -- Enum: rti | complaint | fir | labor | both | none
    template_type   VARCHAR(50),
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. SITUATION CHILD TABLES (depend on situations.db_id FK)
-- ─────────────────────────────────────────────────────────────────────────────

-- Entity: SituationRight (@Table name = "situation_rights")
CREATE TABLE IF NOT EXISTS situation_rights (
    id                  BIGSERIAL   PRIMARY KEY,
    situation_db_id     BIGINT      NOT NULL REFERENCES situations(db_id) ON DELETE CASCADE,
    title_en            TEXT,
    title_hi            TEXT,
    description_en      TEXT,
    description_hi      TEXT
);

-- Entity: LawSection (@Table name = "law_sections")
CREATE TABLE IF NOT EXISTS law_sections (
    id                  BIGSERIAL   PRIMARY KEY,
    situation_db_id     BIGINT      NOT NULL REFERENCES situations(db_id) ON DELETE CASCADE,
    section             TEXT,
    act                 TEXT,
    summary_en          TEXT,
    summary_hi          TEXT,
    full_text           TEXT
);

-- Entity: ChecklistItem (@Table name = "checklist_items")
CREATE TABLE IF NOT EXISTS checklist_items (
    id                  BIGSERIAL       PRIMARY KEY,
    situation_db_id     BIGINT          NOT NULL REFERENCES situations(db_id) ON DELETE CASCADE,
    checklist_id        VARCHAR(255),
    item_en             TEXT,
    item_hi             TEXT,
    required            BOOLEAN         NOT NULL DEFAULT TRUE
);

-- Entity: ProcedureStep (@Table name = "procedure_steps")
CREATE TABLE IF NOT EXISTS procedure_steps (
    id                  BIGSERIAL   PRIMARY KEY,
    situation_db_id     BIGINT      NOT NULL REFERENCES situations(db_id) ON DELETE CASCADE,
    step_number         INTEGER,
    title_en            TEXT,
    title_hi            TEXT,
    description_en      TEXT,
    description_hi      TEXT,
    tip_en              TEXT,
    tip_hi              TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. LAWYERS (parent)
-- Entity: Lawyer (@Table name = "lawyers")
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS lawyers (
    id              BIGSERIAL       PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL,
    state           VARCHAR(255)    NOT NULL,
    city            VARCHAR(255)    NOT NULL,
    phone           VARCHAR(50)     NOT NULL,
    email           VARCHAR(255)    NOT NULL,
    organization    TEXT,
    pro_bono        BOOLEAN         NOT NULL DEFAULT TRUE,
    experience      INTEGER,
    -- Unique business constraint from MongoDB
    bar_council_id  VARCHAR(255)    NOT NULL UNIQUE,
    rating          DOUBLE PRECISION DEFAULT 5.0,
    location_link   TEXT,
    -- Coordinates for map display
    lat             DOUBLE PRECISION,
    lng             DOUBLE PRECISION,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- @ElementCollection for List<String> specializations
-- @CollectionTable(name = "lawyer_specializations")
CREATE TABLE IF NOT EXISTS lawyer_specializations (
    lawyer_id       BIGINT          NOT NULL REFERENCES lawyers(id) ON DELETE CASCADE,
    specialization  VARCHAR(255)    NOT NULL
);

-- @ElementCollection for List<String> languages
-- @CollectionTable(name = "lawyer_languages")
CREATE TABLE IF NOT EXISTS lawyer_languages (
    lawyer_id   BIGINT          NOT NULL REFERENCES lawyers(id) ON DELETE CASCADE,
    language    VARCHAR(100)    NOT NULL
);

-- @ElementCollection for List<String> availableFor
-- @CollectionTable(name = "lawyer_available_for")
CREATE TABLE IF NOT EXISTS lawyer_available_for (
    lawyer_id       BIGINT          NOT NULL REFERENCES lawyers(id) ON DELETE CASCADE,
    available_for   VARCHAR(255)    NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. INDEXES — for commonly queried columns
-- ─────────────────────────────────────────────────────────────────────────────

-- Situations: slug lookups by frontend
CREATE INDEX IF NOT EXISTS idx_situations_situation_id ON situations(situation_id);
-- Situations: category filter
CREATE INDEX IF NOT EXISTS idx_situations_category ON situations(category);

-- Lawyers: geographic/state filter
CREATE INDEX IF NOT EXISTS idx_lawyers_state ON lawyers(state);
CREATE INDEX IF NOT EXISTS idx_lawyers_city ON lawyers(city);
-- Lawyers: pro bono filter
CREATE INDEX IF NOT EXISTS idx_lawyers_pro_bono ON lawyers(pro_bono);

-- Users: username lookup (used by Spring Security)
CREATE INDEX IF NOT EXISTS idx_app_users_username ON app_users(username);
CREATE INDEX IF NOT EXISTS idx_app_users_email ON app_users(email);
